---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: istio-helm-repo
  namespace: flux-system
spec:
  interval: 2h0m0s
  url: https://istio-release.storage.googleapis.com/charts
