---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-ingress
  namespace: istio-ingress
spec:
  releaseName: istio-ingress
  dependsOn:
    - name: istio-base
      namespace: istio-system
    - name: istio-istiod
      namespace: istio-system
  chart:
    spec:
      chart: gateway
      version: "1.18.2"
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: istio-helm-repo
        namespace: flux-system
      interval: 1m
  interval: 5m
