---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-istiod
  namespace: istio-system
spec:
  releaseName: istio-istiod
  dependsOn:
    - name: istio-base
      namespace: istio-system
  chart:
    spec:
      interval: 1m
      chart: istiod
      version: "1.21.2"
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: istio-helm-repo
        namespace: flux-system
  interval: 5m
