---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-ingress
  namespace: istio-system
spec:
  releaseName: istio-ingress
  chart:
    spec:
      chart: istio/gateway
      version: "1.18.2"
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: istio-helm-repo
  interval: 1m0s
