apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: install
  namespace: flux-system 
spec:
  interval: 5m
  retryInterval: 30s
  sourceRef:
    kind: GitRepository
    name: networking-repo
    namespace: flux-system
  path: ./metalab/base/manifests
  prune: true
